# Generated by Django 4.0.4 on 2022-05-23 01:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_birth_day_person_birth_date_person_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 23, 1, 55, 13, 451113, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
