# Generated by Django 4.0.4 on 2022-05-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_person_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='score_average',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
